Base:
  seed: 20
  exp_name: "share_base1"

Train:
  num_episodes: 500
  max_steps: 150

  batch_size: 256
  lr: 5e-4
  gamma: 0.95
  tau: 0.01
  noise_std: 0.005
  noise_clip: 0.01

  lrdelay: false

  buffer_size: 10000
  min_buffer_size: 1024

  update_freq: 10
  update_iterations: 20

  env_random: true
  env_progress_random: true
  env_progress_regen_episode: 100

  ckp_save_interval: 10
  ckp_score_threshold: 300

Model:
  share: true

  hunter_lrdecay: false
  hunter_orthogonalize: false

  target_lrdecay: false
  target_orthogonalize: false

Reward: 
  capture_reward_w: 2.0
  chase_reward_w: 0.8
  escape_reward_w: 0.4
  safe_penalty_w: 0.7

Env:
  time_step: 0.5  
  # 任务参数
  map_size: 500       # m
  num_obstacle: [10, 20]
  num_hunters: [4, 8]
  num_targets: [2, 6]

  # 随机生成参数
  obstacle_margin: 0.1  # [0 ~ 0.5)
  hunter_margin: 0.2    # [0 ~ 0.5)
  target_margin: 0.2    # [0 ~ 0.5)

  obstacle_radius_range: [5, 20]
  obstacle_height_range: [3, 30]
  obstacle_speed: 0.0
  hunter_init_height: 10
  target_init_height: 10

  collision_dist: 10  # m
  escape_dist: 30
  escape_angle: 30

Hunter:
  # 运动性能配置
  action_dim: 2
  max_acc: 5.0      # m/s^2
  max_vel: 20.0       # m/s

  # 探测性能配置
  lidar_beams: 32
  max_lidar_dist: 50
  
  # 协作性能配置
  # Hunter 最大相互通信距离， -1表示无限  
  max_comm_radius: 100 # m
  # Hunter 最多考虑的队友数量
  max_comm_num: 2

Target:
  
  # 运动性能配置
  action_dim: 2
  max_acc: 5.0      # m/s^2
  max_vel: 20.0       # m/s

  # 探测性能配置
  lidar_beams: 32
  max_lidar_dist: 50

  # 对抗性能配置，同时考虑3个Hunter的位置
  max_hunter_num: 3

